const assert=require('node:assert/strict'),W=require('../engine'),data=require('../dictionary.json'),e=W.createEngine(data);
let passed=0;function test(name,fn){fn();passed++;console.log('PASS',name);}async function atest(name,fn){await fn();passed++;console.log('PASS',name);}
const draft=(word,r,c,dr=0,dc=1)=>[...word].map((letter,i)=>({r:r+dr*i,c:c+dc*i,letter}));
const empty=()=>({opening:false,seedWords:[],cells:Array.from({length:15},()=>Array.from({length:15},()=>({playable:true,letter:null,owner:null,colour:'#fff',seedId:null})))});
function put(b,word,r,c,dr=0,dc=1,owner='computer'){for(const t of draft(word,r,c,dr,dc))Object.assign(W.cell(b,t.r,t.c),{letter:t.letter,owner});return b;}
function sFor(b,rack,phase='player'){return {...e.fresh(),board:b,racks:{player:rack,computer:rack},phase,shots:{player:phase==='computer'?1:0,computer:0}};}
(async()=>{
const smile=W.makeBoard('smiley',1);
test('Smiley: vertical EYE words, mouth SMILE, black yellow artwork and blocked corners',()=>{assert.deepEqual(W.sequences(smile).map(w=>w.word).sort(),['EYE','EYE','SMILE']);assert.equal(W.cell(smile,11,5).letter,'S');assert.equal(W.cell(smile,11,5).colour,'#172b38');for(const c of [4,10]){assert(!W.cell(smile,10,c).playable);assert(W.cell(smile,10,c).decorative);}assert.equal(W.tally(smile).neutral,11);});
const help=[{r:4,c:3,letter:'H'},{r:4,c:5,letter:'L'},{r:4,c:6,letter:'P'}];
test('User HELP example: first play keeps complete EYE and removes only unused seeds',()=>{let s=sFor(smile,[...'HLPABCDE']);const out=e.commit(s,help);assert(out.ok);assert.equal(out.state.shots.player,1);assert.equal(out.state.phase,'computer');const b=out.state.board;assert(!b.opening);assert.equal(W.tally(b).player,6);assert.equal(W.cell(b,6,4).letter,'E');assert.equal(W.cell(b,4,10).letter,null);assert.equal(W.cell(b,11,5).letter,null);assert.equal(W.cell(b,11,5).colour,'#172b38');assert(W.cell(b,11,5).playable);assert(e.restore(JSON.stringify(out.state)));});
test('THIS crosses mouth I and claims THIS plus SMILE exactly once',()=>{const d=[{r:9,c:7,letter:'T'},{r:10,c:7,letter:'H'},{r:12,c:7,letter:'S'}],out=e.commit(sFor(smile,[...'THSABCDE']),d);assert(out.ok);assert.equal(W.tally(out.state.board).player,8);assert.equal(W.cell(out.state.board,4,4).letter,null);assert.equal(W.cell(out.state.board,11,5).owner,'player');});
test('First move must reuse a seed letter in the main word, not mere side adjacency',()=>{const r=e.validate(smile,draft('CAT',3,3),[...'CAT']);assert(!r.ok);assert.match(r.error,/starting letter/);});
test('Invalid opening cannot remove seeds or spend a turn',()=>{const s=sFor(smile,[...'QXABCDEH']),before=JSON.stringify(s);assert(!e.commit(s,[{r:4,c:3,letter:'Q'},{r:4,c:5,letter:'X'}]).ok);assert.equal(JSON.stringify(s),before);});
test('Captures include directly reused full words without recursive capture',()=>{const b=put(put(empty(),'SMILE',7,5),'SAD',7,5,1,0),d=[{r:5,c:7,letter:'T'},{r:6,c:7,letter:'H'},{r:8,c:7,letter:'S'}],out=e.commit(sFor(b,[...'THSABCDE']),d);assert(out.ok);assert.deepEqual(W.tally(out.state.board),{player:8,computer:2,neutral:0});assert.equal(W.cell(out.state.board,8,5).owner,'computer');assert.equal(W.cell(out.state.board,9,5).owner,'computer');});
test('Computer captures back the exact word chain directly reused, not indirectly touched words',()=>{let b=put(put(empty(),'SMILE',7,5,0,1,'player'),'THIS',5,7,1,0,'player');put(b,'SAD',7,5,1,0,'player');const s=sFor(b,[...'TLEABCDE'],'computer'),out=e.commit(s,draft('TLE',9,7,1,0),'computer');assert(out.ok);assert.equal(W.tally(out.state.board).computer,11);assert.equal(W.cell(out.state.board,8,5).owner,'player');assert.equal(W.cell(out.state.board,9,5).owner,'player');});
test('Valid crossing constrained by two existing perpendicular words',()=>{const b=put(put(empty(),'CAT',5,5,1,0),'BED',5,7,1,0);assert(e.validate(b,[{r:6,c:4,letter:'C'},{r:6,c:6,letter:'R'}],['C','R']).ok);});
test('Legal main word that creates an illegal perpendicular word is rejected',()=>{const b=put(empty(),'QUIZ',6,6);assert(!e.validate(b,draft('CAT',7,6),[...'CAT']).ok);});
test('Duplicate-letter counts and single-letter full extensions',()=>{const b=put(empty(),'BE',7,5);assert(e.validate(b,draft('LL',7,7),['L','L']).ok);assert(!e.validate(b,draft('LL',7,7),['L','A']).ok);const cat=put(empty(),'CAT',7,5);assert(e.validate(cat,draft('S',7,8),['S']).ok);assert(!e.validate(cat,draft('Q',7,8),['Q']).ok);});
test('Overwrites, gaps, off-board tiles, decorative corners and nonlinear moves rejected',()=>{const b=put(empty(),'CAT',7,5);assert(!e.validate(b,draft('S',7,5),['S']).ok);assert(!e.validate(b,[{r:7,c:8,letter:'S'},{r:7,c:10,letter:'T'}],['S','T']).ok);assert(!e.validate(b,draft('AT',14,14),['A','T']).ok);assert(!e.validate(smile,draft('A',10,4),['A']).ok);assert(!e.validate(b,[{r:6,c:5,letter:'A'},{r:8,c:7,letter:'T'}],['A','T']).ok);});
test('50 generated boards have valid seed topology, colours and a connected playable silhouette',()=>{const signatures=new Set(),sizes=new Set();for(let i=0;i<50;i++){const b=W.makeBoard(i%2?'random':'hashtag',i*317+9);assert(b.seedWords.length>=2);assert(W.sequences(b).every(w=>e.dict.has(w.word)));signatures.add(JSON.stringify(b.cells.map(row=>row.map(c=>c.playable))));sizes.add(b.cells.length+'x'+b.cells[0].length);const cells=[];for(let r=0;r<b.cells.length;r++)for(let c=0;c<b.cells[r].length;c++)if(W.cell(b,r,c).playable)cells.push([r,c]);const seen=new Set(),q=[cells[0]];while(q.length){const [r,c]=q.pop();if(seen.has(W.key(r,c)))continue;seen.add(W.key(r,c));for(const [dr,dc]of [[0,1],[1,0],[0,-1],[-1,0]])if(W.cell(b,r+dr,c+dc)?.playable&&!seen.has(W.key(r+dr,c+dc)))q.push([r+dr,c+dc]);}assert.equal(seen.size,cells.length);}assert(signatures.size>15);assert(sizes.size>5);});
await atest('Timed-out search is never exhaustion, including expired computer turn',async()=>{const r=await W.searchMoves(smile,e.lex,e.dict,{deadline:Date.now()-1});assert(!r.complete);assert.equal(r.moves.length,0);const s={...sFor(smile,[...'ABCDEFGH'],'computer'),botStartedAt:Date.now()-20000};const out=await e.computerTurn(s,{deadline:Date.now()-1});assert.equal(out.lastMove.kind,'pass');assert.equal(out.shots.computer,1);assert.equal(out.phase,'player-refill');assert(out.board.opening);});
await atest('Pass keeps zero through eight exact tile identities and consumes precisely one turn',async()=>{const s=await e.newMatch('hashtag','easy',8,330);for(let n=0;n<=8;n++){const indices=Array.from({length:n},(_,i)=>i),keep=indices.map(i=>s.racks.player[i]),out=await e.pass(s,indices,true,W.seeded(n));assert(out.ok);assert.equal(out.state.shots.player,1);assert.equal(out.state.phase,'computer');assert(W.fits(W.count(keep),W.count(out.state.racks.player)));assert.equal(out.state.racks.player.length,8);assert(!(await e.pass(out.state,[])).ok);}const unchanged=await e.pass(s,[0,1,2,3,4,5,6,7]);assert.deepEqual(unchanged.state.racks.player,s.racks.player);assert(!e.commit(unchanged.state,help).ok);});
await atest('Impossible retained letters require explicit consent; retaining all is a valid pass',async()=>{const small=W.createEngine({words:['CAT'],common:['CAT'],stretch:[]}),b=empty();for(const row of b.cells)for(const sq of row)sq.playable=false;for(let c=5;c<8;c++)b.cells[7][c].playable=true;put(b,'C',7,5);const s=sFor(b,[...'ZZZZZZZZ']);const blocked=await small.pass(s,[0,1,2,3,4,5,6]);assert(!blocked.ok);assert.equal(blocked.reason,'retained-block');assert.equal(s.shots.player,0);const agreed=await small.pass(s,[0,1,2,3,4,5,6],true,W.seeded(2));assert(agreed.ok);assert.equal(W.count(agreed.state.racks.player).Z,7);const whole=await small.pass(s,[0,1,2,3,4,5,6,7]);assert(whole.ok);});
test('Difficulty recognises familiarity, not word length; repeated placements do not multiply recognition chances',()=>{assert(e.recognition('CAT','easy')>e.recognition('QUARTZ','easy'));assert(e.recognition('QUARTZ','hard')>e.recognition('QUARTZ','easy'));const b=put(empty(),'QUART',7,5),s=sFor(b,[...'ZABCDEFG'],'computer');s.difficulty='easy';const m={word:'QUARTZ',draft:draft('Z',7,10),needs:{Z:1}};assert.equal(e.chooseComputerMove(s,Array(1000).fill(m),()=>.5),null);s.difficulty='hard';assert(e.chooseComputerMove(s,[m],()=>.5));});
await atest('Ten shots each including passes end in a tile-count winner or draw; no eleventh action',async()=>{const s=await e.newMatch('hashtag','easy',8,111);s.shots={player:9,computer:9};s.revision=18;const p=await e.pass(s,[0,1,2,3,4,5,6,7]);assert(p.ok);assert.equal(p.state.shots.player,10);const c=await e.computerTurn(p.state,{deadline:Date.now()-1});assert.equal(c.phase,'finished');assert.deepEqual(c.shots,{player:10,computer:10});assert(!e.commit(c,help).ok);assert(!(await e.pass(c,[])).ok);assert(e.restore(JSON.stringify(c)));});
await atest('Exhausted board finishes gracefully without inventing a move',async()=>{const b=empty();for(const row of b.cells)for(const sq of row)sq.playable=false;b.cells[7][7]={playable:true,letter:'A',owner:'player'};const g=await e.generate(b,[],8);assert.equal(g.status,'exhausted');const s=sFor(b,[...'ABCDEFGH']);s.phase='player-refill';assert.equal((await e.refillPlayer(s)).phase,'finished');});
await atest('Committed ownership, racks, counters and pending computer seed/deadline restore exactly',async()=>{let s=await e.newMatch('smiley','normal',8,98);assert.deepEqual(e.restore(JSON.stringify(s)),s);let m=await e.findMove(s.board,s.racks.player);const out=e.commit(s,m.draft);assert(out.ok);assert.deepEqual(e.restore(JSON.stringify(out.state)),out.state);assert(!e.commit(out.state,m.draft).ok);let broken=W.clone(out.state);broken.shots.computer=10;assert.equal(e.restore(JSON.stringify(broken)),null);assert.equal(e.restore('{oops'),null);assert.equal(e.restore(JSON.stringify({version:1})),null);});
let moves=0,passes=0,early=0;console.time('simulation');
await atest('Nine full matches across three board choices and every difficulty',async()=>{for(const type of ['smiley','hashtag','random'])for(const difficulty of ['easy','normal','hard']){
 let s=await e.newMatch(type,difficulty,8,201+early);const rng=W.seeded(62);let actions=0;
 while(s.phase!=='finished'&&actions<20){
  if(s.phase==='player-refill')s=await e.refillPlayer(s,rng);if(s.phase==='finished')break;
  assert.equal(s.phase,'player');const m=await e.findMove(s.board,s.racks.player);
  if(m&&rng()>.15){assert(e.validate(s.board,m.draft,s.racks.player).ok);const out=e.commit(s,m.draft);assert(out.ok);s=out.state;moves++;}else{const out=await e.pass(s,[],true,rng);assert(out.ok);s=out.state;passes++;}actions++;assert(e.restore(JSON.stringify(s)));
  if(s.phase==='finished')break;const old=s; s=await e.computerTurn(s,{rng,deadline:Date.now()+14000});actions++;
  if(s.lastMove?.by==='computer'){if(s.lastMove.kind==='play')moves++;else passes++;}
  assert(s.shots.player<=10&&s.shots.computer<=10);assert(e.restore(JSON.stringify(s)));assert(W.sequences(s.board).every(w=>e.dict.has(w.word)));
 }
 assert.equal(s.phase,'finished');if(s.shots.computer<10)early++;console.log('SIM',type,difficulty,JSON.stringify({shots:s.shots,tiles:W.tally(s.board),reason:s.finishReason}));
}});
console.timeEnd('simulation');console.log(JSON.stringify({passed,matches:9,verifiedPlays:moves,passes,earlyFinished:early},null,2));
})().catch(err=>{console.error(err);process.exit(1);});
