/* Actual bundled scripts in a simulated DOM. Not physical device/browser layout testing. */
const {parseHTML}=require('linkedom'),vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
const html=fs.readFileSync('dist/wordshape.html','utf8');let passed=0;
function boot(saved=null,broken=false){const {document,window:dom}=parseHTML(html),store=new Map(saved?[['wordramble-v2',saved]]:[]);const sandbox={document,console,setTimeout,clearTimeout,requestAnimationFrame:f=>setTimeout(f,16),cancelAnimationFrame:clearTimeout,localStorage:{getItem:k=>{if(broken)throw Error('denied');return store.get(k)||null;},setItem:(k,v)=>{if(broken)throw Error('denied');store.set(k,v);}},addEventListener:dom.addEventListener.bind(dom)};sandbox.window=sandbox;const ctx=vm.createContext(sandbox),read=s=>vm.runInContext(s,ctx),el=id=>document.getElementById(id);for(const id of ['difficulty','capacity'])Object.defineProperty(el(id),'value',{value:id==='difficulty'?'easy':'8',writable:true});el('dialog').showModal=()=>{};el('dialog').close=()=>{};const rect=(x,y,w,h)=>({left:x,top:y,right:x+w,bottom:y+h,width:w,height:h});Object.defineProperties(el('viewport'),{clientWidth:{value:420},clientHeight:{value:500}});el('viewport').scrollLeft=el('viewport').scrollTop=0;el('viewport').getBoundingClientRect=()=>rect(20,150,420,500);el('board').getBoundingClientRect=()=>rect(20-el('viewport').scrollLeft,150-el('viewport').scrollTop,650*read('zoom'),650*read('zoom'));el('passBox').getBoundingClientRect=()=>rect(20,740,420,110);document.elementFromPoint=(x,y)=>y>=740&&y<=850?el('passBox'):document.body;for(const id of ['viewport','rackCard']){el(id).setPointerCapture=()=>{};el(id).releasePointerCapture=()=>{};}for(const m of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))if(!m[0].includes('application/json'))read(m[1]);return {document,store,dom,read,el,click:id=>el(id).click(),tile:i=>document.querySelector('#rack [data-tile="'+i+'"]'),cell:(r,c)=>document.querySelector('[data-r="'+r+'"][data-c="'+c+'"]'),event:(target,type,props)=>{const e=new dom.Event(type,{bubbles:true,cancelable:true});Object.assign(e,{button:0,pointerType:'touch',pointerId:1,clientX:100,clientY:900,...props});target.dispatchEvent(e);}};}
async function settled(h){for(let i=0;i<3000;i++){await new Promise(r=>setTimeout(r,10));if(!h.read('busy||computerJob'))return;}throw Error('UI did not settle');}function pass(n){passed++;console.log('PASS',n);}
(async()=>{let h=boot();h.click('newGame');await settled(h);h.click('fit');assert.equal(h.read('state.phase'),'player');assert.equal(h.document.querySelectorAll('#rack .tile').length,8);pass('Start creates playable match and eight rack tiles');
const rack=h.read('state.racks.player.join("")');h.tile(0).click();h.cell(4,3).click();assert.equal(h.read('draft.size'),1);h.click('recall');assert.equal(h.read('draft.size'),0);assert.equal(h.read('state.racks.player.join("")'),rack);pass('Tap placement and recall preserve all rack identities');
for(let n=0;n<=8;n++){h.click('pass');for(let i=0;i<n;i++)h.tile(i).click();assert.equal(h.read('keeps.size'),n);h.click('cancelPass');assert.equal(h.read('state.shots.player'),0);assert.equal(h.read('state.racks.player.join("")'),rack);}pass('Pass mode supports zero through eight keeps; cancellation costs no turn');
let src=h.tile(0);h.event(src,'pointerdown',{});const z=h.read('zoom'),x=20+(4+3*43+20)*z,y=150+(4+4*43+20)*z;h.event(h.el('rackCard'),'pointermove',{clientX:x+44,clientY:y+76});assert(h.cell(4,3).classList.contains('target'));assert.equal(h.el('ghost').style.left,x+'px');h.event(h.el('rackCard'),'pointerup',{clientX:x+44,clientY:y+76});assert.equal(h.read('draft.get(0).c'),3);assert.equal(h.read('draft.get(0).r'),4);assert.equal(h.document.querySelectorAll('.target').length,0);pass('Raised tile top-left aims, highlights and drops on expected cell');
h.click('recall');for(const termination of ['pointercancel','lostpointercapture']){h.event(h.tile(0),'pointerdown',{pointerId:2});h.event(h.el('rackCard'),'pointermove',{pointerId:2,clientX:300,clientY:300});h.event(h.el('rackCard'),termination,{pointerId:2});assert.equal(h.read('gesture'),null);assert.equal(h.read('pointers.size'),0);assert.equal(h.read('draft.size'),0);}h.event(h.tile(0),'pointerdown',{});h.event(h.el('rackCard'),'pointermove',{clientX:1000,clientY:1000});h.event(h.el('rackCard'),'pointerup',{clientX:1000,clientY:1000});assert.equal(h.read('draft.size'),0);pass('Pointer cancel, capture loss and outside drop preserve letters');
h.event(h.cell(5,5),'pointerdown',{pointerId:3,clientX:120,clientY:300});h.event(h.cell(5,6),'pointerdown',{pointerId:4,clientX:220,clientY:300});h.event(h.el('viewport'),'pointermove',{pointerId:4,clientX:320,clientY:300});assert(h.read('zoom')>z);h.event(h.el('viewport'),'pointerup',{pointerId:3});h.event(h.el('viewport'),'pointerup',{pointerId:4});h.click('fit');assert.equal(h.read('zoom'),z);assert.equal(h.read('draft.size'),0);pass('Two-pointer zoom and fit restore scale without tile loss');
h.click('pass');h.event(h.tile(0),'pointerdown',{});h.event(h.el('rackCard'),'pointermove',{clientX:144,clientY:866});h.event(h.el('rackCard'),'pointerup',{clientX:144,clientY:866});assert(h.read('keeps.has(0)'));h.click('cancelPass');pass('Drag into keep tray selects letter separately from placement');
h.read('state.racks.player=[..."HLPABCDE"];render()');for(const [i,c] of [[0,3],[1,5],[2,6]]){h.tile(i).click();h.cell(4,c).click();}h.click('submit');const pending=h.store.get('wordramble-v2');assert.equal(h.read('state.shots.player'),1);assert.equal(h.read('W.tally(state.board).player'),6);assert.equal(h.read('W.cell(state.board,11,5).letter'),null);h.click('submit');assert.equal(h.read('state.shots.player'),1);await settled(h);assert.equal(h.read('state.shots.computer'),1);pass('HELP commits once, preserves EYE, clears unused seeds and computer takes one turn');
const resumed=boot(pending);await settled(resumed);assert.equal(resumed.read('state.shots.player'),1);assert.equal(resumed.read('state.shots.computer'),1);pass('Refreshing a pending computer turn resumes without double counting');
const saved=h.store.get('wordramble-v2'),restored=boot(saved);assert.equal(restored.el('playerTiles').textContent,h.el('playerTiles').textContent);assert.equal(restored.read('draft.size'),0);pass('Owned tiles, counters and rack restore through bundled UI');
h.click('pass');for(let i=0;i<8;i++)h.tile(i).click();const kept=h.read('state.racks.player.join("")');h.click('completePass');await settled(h);assert.equal(h.read('state.shots.player'),2);assert.equal(h.read('state.shots.computer'),2);assert.equal(h.read('state.racks.player.join("")'),kept);pass('Keep-all completed pass preserves rack and takes one turn each');
const before=h.store.get('wordramble-v2');h.tile(0).click();h.cell(0,7).click();h.click('submit');assert.equal(h.store.get('wordramble-v2'),before);h.click('recall');pass('Invalid draft cannot change saved ownership or turns');
const denied=boot(null,true);denied.click('newGame');await settled(denied);assert.equal(denied.read('state.phase'),'player');assert(denied.el('storage').textContent.includes('save'));const corrupt=boot('{bad');assert.equal(corrupt.read('state'),null);pass('Unavailable storage and malformed saves recover safely');
console.log(JSON.stringify({passed,environment:'LinkeDOM simulation, synthetic pointer coordinates; no browser layout or physical iPhone testing'},null,2));
})().catch(e=>{console.error(e);process.exitCode=1;});
